from fastapi import APIRouter
from .controllers.merchant_user_admin_controller import merchant_user_admin_router
from .controllers.merchant_user import merchant_user_router
from .controllers.merchant_controller import merchant_router
from .controllers.authentication_controller import authenticaion_router
merchants_routers = APIRouter()

merchants_routers.include_router(authenticaion_router)
merchants_routers.include_router(merchant_router)
merchants_routers.include_router(merchant_user_router)
merchants_routers.include_router(merchant_user_admin_router)