"""alter product_option_group_id

Revision ID: 1007835febba
Revises: 4527d1c0a23d
Create Date: 2023-12-13 10:17:05.143526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1007835febba'
down_revision: Union[str, None] = '4527d1c0a23d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_options', sa.Column('product_option_group_id', sa.Integer(), nullable=True))
    op.drop_constraint('product_options_option_group_id_fkey', 'product_options', type_='foreignkey')
    op.create_foreign_key(None, 'product_options', 'product_option_groups', ['product_option_group_id'], ['id'])
    op.drop_column('product_options', 'option_group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_options', sa.Column('option_group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'product_options', type_='foreignkey')
    op.create_foreign_key('product_options_option_group_id_fkey', 'product_options', 'product_option_groups', ['option_group_id'], ['id'])
    op.drop_column('product_options', 'product_option_group_id')
    # ### end Alembic commands ###
