"""add relationships to IFoodOrder with Order

Revision ID: 3cf25f6f1419
Revises: 28e7f33fd0e1
Create Date: 2024-01-15 16:35:47.012295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cf25f6f1419'
down_revision: Union[str, None] = '28e7f33fd0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
