"""add relationships to IFoodOrder with Order

Revision ID: 5fca827084a1
Revises: 52dd151ee07e
Create Date: 2024-01-15 16:53:52.577832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fca827084a1'
down_revision: Union[str, None] = '52dd151ee07e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
