"""add relationships to IFoodOrder with Order

Revision ID: 63d0f24b0e59
Revises: 3cf25f6f1419
Create Date: 2024-01-15 16:44:37.817083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63d0f24b0e59'
down_revision: Union[str, None] = '3cf25f6f1419'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
