"""add timezones

Revision ID: 6ce41b48a551
Revises: 86d9dff9713e
Create Date: 2024-01-10 16:31:37.395974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '6ce41b48a551'
down_revision: Union[str, None] = '86d9dff9713e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'ordertimming', ['IMMEDIATE', 'SCHEDULED', 'TEST'],
                        [TableReference('orders', 'order_timing')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'ordertimming', ['IMMEDIATE', 'SCHEDULED'],
                        [TableReference('orders', 'order_timing')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
