"""create routes service

Revision ID: 74859dad9a4b
Revises: 825c78523615
Create Date: 2024-01-10 13:38:05.593082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74859dad9a4b'
down_revision: Union[str, None] = '825c78523615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_item_options', sa.Column('product_option_group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_item_options', 'product_option_groups', ['product_option_group_id'], ['id'])
    op.add_column('order_items', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_items', 'orders', ['product_id'], ['id'])
    op.alter_column('orders', 'order_timing',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=True,
               postgresql_using="order_timing::timestamp without time zone")
    # op.alter_column('orders', 'order_timing',
    #            existing_type=sa.VARCHAR(),
    #            type_=sa.DateTime(),
    #            existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'order_timing',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'product_id')
    op.drop_constraint(None, 'order_item_options', type_='foreignkey')
    op.drop_column('order_item_options', 'product_option_group_id')
    # ### end Alembic commands ###
