from enum import Enum


class DietaryRestriction(Enum):
    VEGETARIAN='VEGETARIAN'
    VEGAN='VEGAN'
    ORGANIC='ORGANIC'
    GLUTEN_FREE='GLUTEN_FREE'
    SUGAR_FREE='SUGAR_FREE'
    LAC_FREE='LAC_FREE'
    ALCOHOLIC_DRINK='ALCOHOLIC_DRINK'
    NATURAL='NATURAL'
    ZERO='ZERO'
    DIET='DIET'