"""Alterando Module Permissions

Revision ID: 0218ca14f0cf
Revises: 8e4c66af105d
Create Date: 2024-02-13 18:07:04.959872

"""
from typing import Sequence, Union

from migrations import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0218ca14f0cf'
down_revision: Union[str, None] = '8e4c66af105d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
