"""Alterando Module Permissions

Revision ID: 2484add3b822
Revises: 5fca827084a1
Create Date: 2024-02-13 16:22:50.119921

"""
from typing import Sequence, Union

from migrations import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2484add3b822'
down_revision: Union[str, None] = '5fca827084a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # Deletar a coluna 'permissions' existente
    op.drop_column('merchant_users', 'permissions')

    # Recriar a coluna 'permissions' com o novo tipo
    default = "{'MERCHANT', 'ROUTES', 'ORDERS', 'PRODUCTS', 'COMMANDS'}"
    op.add_column('merchant_users', sa.Column('permissions', sa.ARRAY(sa.String()), nullable=True, server_default=default))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('OWNER', 'ADM', 'GARSON', 'CHEF', 'DRIVER', name='merchantuserrole').create(op.get_bind())
    op.alter_column('merchant_users', 'permissions',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ENUM('OWNER', 'ADM', 'GARSON', 'CHEF', 'DRIVER', name='merchantuserrole'),
               existing_nullable=True)
    # ### end Alembic commands ###
