"""define_auto_increment_to_all_tables_id

Revision ID: 2769d075ffd3
Revises: 91a06bc5e16a
Create Date: 2024-03-12 16:43:12.133344

"""
from typing import Sequence, Union

from migrations import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2769d075ffd3'
down_revision: Union[str, None] = '91a06bc5e16a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_merchant_users_id', table_name='merchant_users')
    op.drop_index('ix_merchants_id', table_name='merchants')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_merchants_id', 'merchants', ['id'], unique=False)
    op.create_index('ix_merchant_users_id', 'merchant_users', ['id'], unique=False)
    # ### end Alembic commands ###
