"""alter orders relations ships

Revision ID: 43b4823aa791
Revises: 6d36096845ce
Create Date: 2024-01-11 17:43:19.254421

"""
from typing import Sequence, Union

from migrations import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43b4823aa791'
down_revision: Union[str, None] = '6d36096845ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
