"""Alterando Module Permissions

Revision ID: 8e4c66af105d
Revises: 2484add3b822
Create Date: 2024-02-13 18:06:45.669010

"""
from typing import Sequence, Union

from migrations import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e4c66af105d'
down_revision: Union[str, None] = '2484add3b822'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('OWNER', 'ADM', 'GARSON', 'CHEF', 'DRIVER', name='merchantuserrole').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('OWNER', 'ADM', 'GARSON', 'CHEF', 'DRIVER', name='merchantuserrole').create(op.get_bind())
    # ### end Alembic commands ###
