"""initial_db

Revision ID: b4b16ec8af3c
Revises: 2f2d53a498fc
Create Date: 2024-06-26 21:38:51.393251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4b16ec8af3c'
down_revision: Union[str, None] = '2f2d53a498fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchants', 'merchant_type')
    op.add_column('option_groups', sa.Column('item_id', sa.UUID(), nullable=True))
    op.drop_constraint('option_groups_product_id_fkey', 'option_groups', type_='foreignkey')
    op.create_foreign_key(None, 'option_groups', 'items', ['item_id'], ['id'])
    op.drop_column('option_groups', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('option_groups', sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'option_groups', type_='foreignkey')
    op.create_foreign_key('option_groups_product_id_fkey', 'option_groups', 'products', ['product_id'], ['id'])
    op.drop_column('option_groups', 'item_id')
    op.add_column('merchants', sa.Column('merchant_type', sa.VARCHAR(length=12), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
