"""create routes service

Revision ID: ba2e72fa4608
Revises: 21b7d5f384d1
Create Date: 2024-01-10 09:58:52.681738

"""
from typing import Sequence, Union

from migrations import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba2e72fa4608'
down_revision: Union[str, None] = '21b7d5f384d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
