"""add relationships to IFoodOrder with Order

Revision ID: cd4489c1837f
Revises: 326aab327c53
Create Date: 2024-01-15 16:47:54.504823

"""
from typing import Sequence, Union

from migrations import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd4489c1837f'
down_revision: Union[str, None] = '326aab327c53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
