"""add timezones

Revision ID: fc677894e445
Revises: 6ce41b48a551
Create Date: 2024-01-10 16:31:48.286433

"""
from typing import Sequence, Union

from migrations import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'fc677894e445'
down_revision: Union[str, None] = '6ce41b48a551'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'ordertimming', ['IMMEDIATE', 'SCHEDULED'],
                        [TableReference('orders', 'order_timing')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'ordertimming', ['IMMEDIATE', 'SCHEDULED', 'TEST'],
                        [TableReference('orders', 'order_timing')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
