"""Mais algo?

Revision ID: 33aad6e6aeba
Revises: 0218ca14f0cf
Create Date: 2024-02-13 18:21:19.327875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33aad6e6aeba'
down_revision: Union[str, None] = '0218ca14f0cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('OWNER', 'ADM', 'GARSON', 'CHEF', 'DRIVER', name='role').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('OWNER', 'ADM', 'GARSON', 'CHEF', 'DRIVER', name='role').create(op.get_bind())
    # ### end Alembic commands ###
