"""alter route fields

Revision ID: 4b82bd212548
Revises: 43b4823aa791
Create Date: 2024-01-12 09:43:41.152291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b82bd212548'
down_revision: Union[str, None] = '43b4823aa791'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('distance', sa.Float(), nullable=True))
    op.add_column('routes', sa.Column('volume', sa.Float(), nullable=True))
    op.drop_column('routes', 'total_distance')
    op.drop_column('routes', 'total_volume')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('total_volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('routes', sa.Column('total_distance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('routes', 'volume')
    op.drop_column('routes', 'distance')
    # ### end Alembic commands ###
