"""add relationships to IFoodOrder with Order

Revision ID: 52dd151ee07e
Revises: aaaf88e8ad9f
Create Date: 2024-01-15 16:51:19.441270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52dd151ee07e'
down_revision: Union[str, None] = 'aaaf88e8ad9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
