"""add_product_option_associations

Revision ID: 63fa27ed3cf7
Revises: 2769d075ffd3
Create Date: 2024-03-19 15:48:08.445333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63fa27ed3cf7'
down_revision: Union[str, None] = '2769d075ffd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_option_associations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('productOption_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['productOption_group_id'], ['product_option_groups.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('orders', sa.Column('command_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'commands', ['command_id'], ['id'])
    op.drop_constraint('product_option_groups_product_id_fkey', 'product_option_groups', type_='foreignkey')
    op.drop_column('product_option_groups', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_option_groups', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('product_option_groups_product_id_fkey', 'product_option_groups', 'products', ['product_id'], ['id'])
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'command_id')
    op.drop_table('product_option_associations')
    # ### end Alembic commands ###
