"""alter caregory

Revision ID: d9d9aa5544ae
Revises: 1007835febba
Create Date: 2024-01-09 12:24:27.041002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9d9aa5544ae'
down_revision: Union[str, None] = '1007835febba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalog_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('catalog_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['catalog_id'], ['catalogs.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('order_customers', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_customers', 'orders', ['order_id'], ['id'])
    op.add_column('order_deliveries', sa.Column('order_id', sa.Integer(), nullable=True))
    order_delivered_by_type = sa.Enum('MERCHANT', 'IFOOD', 'ROTAFOOD', name='orderdeliveredby')

    order_delivered_by_type.create(op.get_bind(), checkfirst=False)

    # Faça a alteração da coluna
    op.alter_column('order_deliveries', 'delivered_by',
                    existing_type=sa.VARCHAR(),
                    type_=order_delivered_by_type,
                    existing_nullable=True,
                    postgresql_using='delivered_by::text::orderdeliveredby')

    # op.alter_column('order_deliveries', 'delivered_by',
    #            existing_type=sa.VARCHAR(),
    #            type_=sa.Enum('MERCHANT', 'IFOOD', 'ROTAFOOD', name='orderdeliveredby'),
    #            existing_nullable=True)
    op.create_foreign_key(None, 'order_deliveries', 'orders', ['order_id'], ['id'])
    op.add_column('order_payments', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_payments', 'orders', ['order_id'], ['id'])
    op.drop_constraint('orders_customer_id_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('orders_merchant_user_id_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('orders_delivery_id_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('orders_payment_id_fkey', 'orders', type_='foreignkey')
    op.drop_column('orders', 'customer_id')
    op.drop_column('orders', 'delivery_id')
    op.drop_column('orders', 'payment_id')
    op.drop_column('orders', 'merchant_user_id')
    op.add_column('product_categories', sa.Column('merchant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product_categories', 'merchants', ['merchant_id'], ['id'])
    op.add_column('product_options', sa.Column('price', sa.Float(), nullable=True))
    op.drop_column('product_options', 'price_value')
    op.drop_column('product_options', 'price_original_value')
    op.add_column('products', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'price')
    op.add_column('product_options', sa.Column('price_original_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('product_options', sa.Column('price_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('product_options', 'price')
    op.drop_constraint(None, 'product_categories', type_='foreignkey')
    op.drop_column('product_categories', 'merchant_id')
    op.add_column('orders', sa.Column('merchant_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('payment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('delivery_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('orders_payment_id_fkey', 'orders', 'order_payments', ['payment_id'], ['id'])
    op.create_foreign_key('orders_delivery_id_fkey', 'orders', 'order_deliveries', ['delivery_id'], ['id'])
    op.create_foreign_key('orders_merchant_user_id_fkey', 'orders', 'merchant_users', ['merchant_user_id'], ['id'])
    op.create_foreign_key('orders_customer_id_fkey', 'orders', 'order_customers', ['customer_id'], ['id'])
    op.drop_constraint(None, 'order_payments', type_='foreignkey')
    op.drop_column('order_payments', 'order_id')
    op.drop_constraint(None, 'order_deliveries', type_='foreignkey')
    op.alter_column('order_deliveries', 'delivered_by',
               existing_type=sa.Enum('MERCHANT', 'IFOOD', 'ROTAFOOD', name='orderdeliveredby'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('order_deliveries', 'order_id')
    op.drop_constraint(None, 'order_customers', type_='foreignkey')
    op.drop_column('order_customers', 'order_id')
    op.drop_table('catalog_items')
    op.drop_table('catalogs')
    # ### end Alembic commands ###
