from fastapi import APIRouter
from .controllers.merchant_user_admin_controller import merchant_user_admin_controller
from .controllers.merchant_user import merchant_user_controller
from .controllers.merchant_controller import merchant_controller
from .controllers.authentication_controller import authenticaion_controller
merchants_routers = APIRouter()

merchants_routers.include_router(authenticaion_controller)
merchants_routers.include_router(merchant_controller)
merchants_routers.include_router(merchant_user_controller)
merchants_routers.include_router(merchant_user_admin_controller)