from enum import Enum


class OrderPickingReplacementOption(Enum):
    STORE_CHOOSE_OTHER_ITEMS = "STORE_CHOOSE_OTHER_ITEMS"
    STORE_CONTACT_CUSTOMER = "STORE_CONTACT_CUSTOMER"
    STORE_CANCEL_ORDER = "STORE_CANCEL_ORDER"
    STORE_REMOVE_ITEMS = "STORE_REMOVE_ITEMS"